In [1]:
# 딥러닝을 구동하는 데 필요한 케라스 함수를 불러옵니다
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
# 필요한 라이브러리 불러옵니다
import numpy as np
import tensorflow as tf

In [9]:
# 실행할 때마다 같은 결과를 출력하기 위해 설정하는 부분입니다.
np.random.seed(3)
tf.random.set_seed(3)

In [10]:
# 준비된 수술 환자 데이터를 불러옴
Data_set = np.loadtxt('../AI-Seminar-01-master/dataset/ThoraricSurgery.csv', delimiter=",")
Data_set

array([[293.  ,   1.  ,   3.8 , ...,   0.  ,  62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88, ...,   0.  ,  60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19, ...,   0.  ,  66.  ,   1.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,  62.  ,   0.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,  58.  ,   1.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,  49.  ,   0.  ]])

In [11]:
# 환자의 기록과 수술 결과를 X와 Y로 구분하여 저장합니다.
X = Data_set[:,0:17]
Y = Data_set[:,17]

속성(정보)은 종양의 유형, 폐활량, 호흡곤란 여부, 기침, 흡연, 천식등의 17가지 환자 상태이고
마지막 18번째는 수술 후 생존 결과로 1이면 생존, 0이면 사망

In [12]:
X[0]

array([293. ,   1. ,   3.8,   2.8,   0. ,   0. ,   0. ,   0. ,   0. ,
         0. ,  12. ,   0. ,   0. ,   0. ,   1. ,   0. ,  62. ])

In [13]:
Y[0]

0.0

In [14]:
# 딥러닝 구조를 결정함(모델을 설정하고 실행하는 부분)
model = Sequential()
model.add(Dense(30, input_dim = 17, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [15]:
# 딥러닝을 실행
model.compile(loss = 'mean_squared_error', optimizer = 'adam', metrics = ['accuracy'])
model.fit(X, Y, epochs = 100, batch_size = 10)

Train on 470 samples
Epoch 1/100
470/470 [==============================] - 0s 796us/sample - loss: 0.1496 - accuracy: 0.8383
Epoch 2/100
470/470 [==============================] - 0s 128us/sample - loss: 0.1445 - accuracy: 0.8447
Epoch 3/100
470/470 [==============================] - 0s 137us/sample - loss: 0.1450 - accuracy: 0.8511
Epoch 4/100
470/470 [==============================] - 0s 121us/sample - loss: 0.1442 - accuracy: 0.8511
Epoch 5/100
470/470 [==============================] - 0s 114us/sample - loss: 0.1449 - accuracy: 0.8511
Epoch 6/100
470/470 [==============================] - 0s 113us/sample - loss: 0.1440 - accuracy: 0.8511
Epoch 7/100
470/470 [==============================] - 0s 140us/sample - loss: 0.1459 - accuracy: 0.8468
Epoch 8/100
470/470 [==============================] - 0s 123us/sample - loss: 0.1470 - accuracy: 0.8511
Epoch 9/100
470/470 [==============================] - 0s 116us/sample - loss: 0.1438 - accuracy: 0.8511
Epoch 10/100
470/470 [============

470/470 [==============================] - 0s 132us/sample - loss: 0.1246 - accuracy: 0.8553
Epoch 79/100
470/470 [==============================] - 0s 130us/sample - loss: 0.1220 - accuracy: 0.8489
Epoch 80/100
470/470 [==============================] - 0s 119us/sample - loss: 0.1382 - accuracy: 0.8511
Epoch 81/100
470/470 [==============================] - 0s 121us/sample - loss: 0.1334 - accuracy: 0.8553
Epoch 82/100
470/470 [==============================] - 0s 123us/sample - loss: 0.1215 - accuracy: 0.8489
Epoch 83/100
470/470 [==============================] - 0s 119us/sample - loss: 0.1251 - accuracy: 0.8596
Epoch 84/100
470/470 [==============================] - 0s 119us/sample - loss: 0.1232 - accuracy: 0.8489
Epoch 85/100
470/470 [==============================] - 0s 110us/sample - loss: 0.1254 - accuracy: 0.8596
Epoch 86/100
470/470 [==============================] - 0s 108us/sample - loss: 0.1281 - accuracy: 0.8617
Epoch 87/100
470/470 [==============================] - 0s 

In [16]:
#결과 확인
print('정확도 %.4f' % model.evaluate(X, Y)[1])

470/470 [==============================] - 0s 191us/sample - loss: 0.1213 - accuracy: 0.8574
정확도 0.8574


In [17]:
new_patient_data = np.array([X[0]])
new_patient_data

array([[293. ,   1. ,   3.8,   2.8,   0. ,   0. ,   0. ,   0. ,   0. ,
          0. ,  12. ,   0. ,   0. ,   0. ,   1. ,   0. ,  62. ]])

In [18]:
predict = model.predict(new_patient_data)
predict

array([[0.01336104]], dtype=float32)