In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
# seed 값 설정
seed = 0
np.random.seed(seed)
tf.random.set_seed(3)

In [3]:
df = pd.read_csv('./dataset/sonar.csv', header=None)

In [4]:
dataset = df.values
X = dataset[:,0:60]
Y_obj = dataset[:,60]
print(X)
print(Y_obj)

[[0.02 0.0371 0.0428 ... 0.0084 0.009 0.0032]
 [0.0453 0.0523 0.0843 ... 0.0049 0.0052 0.0044]
 [0.0262 0.0582 0.1099 ... 0.0164 0.0095 0.0078]
 ...
 [0.0522 0.0437 0.018 ... 0.0138 0.0077 0.0031]
 [0.0303 0.0353 0.049 ... 0.0079 0.0036 0.0048]
 [0.026 0.0363 0.0136 ... 0.0036 0.0061 0.0115]]
['R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 

In [5]:
e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)
print(e)
print(Y)

LabelEncoder()
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [6]:
X = X.astype(np.float32)

In [7]:
# 학습 셋과 테스트 셋의 구분
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=seed)

In [8]:
model = Sequential()
model.add(Dense(24,  input_dim=60, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [9]:

model.compile(loss='mean_squared_error',
            optimizer='adam',
            metrics=['accuracy'])

In [10]:
model.fit(X_train, Y_train, epochs=130, batch_size=5)

Train on 145 samples
Epoch 1/130
145/145 [==============================] - 0s 3ms/sample - loss: 0.2428 - accuracy: 0.6069
Epoch 2/130
145/145 [==============================] - 0s 319us/sample - loss: 0.2310 - accuracy: 0.6000
Epoch 3/130
145/145 [==============================] - 0s 310us/sample - loss: 0.2215 - accuracy: 0.6690
Epoch 4/130
145/145 [==============================] - 0s 366us/sample - loss: 0.2112 - accuracy: 0.7034
Epoch 5/130
145/145 [==============================] - 0s 407us/sample - loss: 0.2025 - accuracy: 0.7448
Epoch 6/130
145/145 [==============================] - 0s 290us/sample - loss: 0.1934 - accuracy: 0.7310
Epoch 7/130
145/145 [==============================] - 0s 303us/sample - loss: 0.1835 - accuracy: 0.7517
Epoch 8/130
145/145 [==============================] - 0s 324us/sample - loss: 0.1735 - accuracy: 0.7586
Epoch 9/130
145/145 [==============================] - 0s 269us/sample - loss: 0.1655 - accuracy: 0.7862
Epoch 10/130
145/145 [==============

145/145 [==============================] - 0s 331us/sample - loss: 0.0110 - accuracy: 1.0000
Epoch 79/130
145/145 [==============================] - 0s 366us/sample - loss: 0.0113 - accuracy: 1.0000
Epoch 80/130
145/145 [==============================] - 0s 462us/sample - loss: 0.0118 - accuracy: 1.0000
Epoch 81/130
145/145 [==============================] - 0s 455us/sample - loss: 0.0098 - accuracy: 1.0000
Epoch 82/130
145/145 [==============================] - 0s 338us/sample - loss: 0.0106 - accuracy: 1.0000
Epoch 83/130
145/145 [==============================] - 0s 455us/sample - loss: 0.0120 - accuracy: 0.9862
Epoch 84/130
145/145 [==============================] - 0s 352us/sample - loss: 0.0109 - accuracy: 1.0000
Epoch 85/130
145/145 [==============================] - 0s 352us/sample - loss: 0.0090 - accuracy: 1.0000
Epoch 86/130
145/145 [==============================] - 0s 359us/sample - loss: 0.0088 - accuracy: 1.0000
Epoch 87/130
145/145 [==============================] - 0s 

In [11]:
# 테스트셋에 모델 적용
print("\n Test Accuracy: %.4f" % (model.evaluate(X_test, Y_test)[1]))

63/63 [==============================] - 0s 2ms/sample - loss: 0.1478 - accuracy: 0.8571

 Test Accuracy: 0.8571
