In [1]:
import pandas as pd
import numpy as np
import os
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split

In [2]:
# 가중치와 옵티마이저를 포함하여 정확히 동일한 모델을 다시 생성합니다
new_model = tf.keras.models.load_model('model4.h5')

# 모델 구조를 출력합니다
new_model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_16 (Dense)             (None, 30)                390       
_________________________________________________________________
dense_17 (Dense)             (None, 12)                372       
_________________________________________________________________
dense_18 (Dense)             (None, 8)                 104       
_________________________________________________________________
dense_19 (Dense)             (None, 1)                 9         
Total params: 875
Trainable params: 875
Non-trainable params: 0
_________________________________________________________________


In [3]:
df_pre = pd.read_csv('./dataset/wine.csv')
df = df_pre.sample(frac = 0.8)

In [4]:
dataset = df.values
X = dataset[:, 0:12]
Y = dataset[:, 12]

In [5]:
X[0]

array([6.80e+00, 2.60e-01, 4.20e-01, 1.70e+00, 4.90e-02, 4.10e+01,
       1.22e+02, 9.93e-01, 3.47e+00, 4.80e-01, 1.05e+01, 8.00e+00])

In [6]:
X

array([[ 6.8 ,  0.26,  0.42, ...,  0.48, 10.5 ,  8.  ],
       [ 6.1 ,  0.27,  0.28, ...,  0.42, 10.2 ,  6.  ],
       [ 8.  ,  0.22,  0.42, ...,  0.69,  8.6 ,  7.  ],
       ...,
       [ 6.2 ,  0.35,  0.25, ...,  0.62,  9.3 ,  6.  ],
       [ 7.1 ,  0.44,  0.27, ...,  0.36, 11.8 ,  6.  ],
       [ 8.5 ,  0.24,  0.47, ...,  0.66,  9.  ,  5.  ]])

In [7]:
predict = new_model.predict(X)

In [8]:
t1 = np.array([[7.100e+00, 3.000e-01, 3.600e-01, 6.800e+00, 5.500e-02, 4.450e+01,
       2.340e+02, 9.972e-01, 3.490e+00, 6.400e-01, 1.020e+01, 6.000e+00]], np.float32)
yhat = new_model.predict(t1)
print(yhat)
result = new_model.predict_classes(t1)
result

[[0.00033642]]


array([[0]])

In [9]:
X[0]

array([6.80e+00, 2.60e-01, 4.20e-01, 1.70e+00, 4.90e-02, 4.10e+01,
       1.22e+02, 9.93e-01, 3.47e+00, 4.80e-01, 1.05e+01, 8.00e+00])

In [10]:
Y[0]

0.0

In [11]:
new_model.predict_classes(X)

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [12]:
predicy01 = np.argmax(predict, 1)
predicy01

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [13]:
print("\n Test Accuracy: %.4f" % (new_model.evaluate(X, Y)[1]))  # 불러온 모델로 테스트 실행

5197/5197 [==============================] - 0s 43us/sample - loss: 0.0705 - accuracy: 0.9771

 Test Accuracy: 0.9771


In [14]:
seed = 0
# 학습셋과 테스트셋을 나눔
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=seed)

In [15]:
print("\n Test Accuracy: %.4f" % (new_model.evaluate(X_test, Y_test)[1]))  # 불러온 모델로 테스트 실행

1560/1560 [==============================] - 0s 27us/sample - loss: 0.0715 - accuracy: 0.9763

 Test Accuracy: 0.9763


In [16]:
print("\n Test Accuracy: %.4f" % (new_model.evaluate(X_test, Y_test)[1]))  # 불러온 모델로 테스트 실행

1560/1560 [==============================] - 0s 26us/sample - loss: 0.0715 - accuracy: 0.9763

 Test Accuracy: 0.9763


In [17]:
print("\n Test Accuracy: %.4f" % (new_model.evaluate(X, Y)[1]))  # 불러온 모델로 테스트 실행

5197/5197 [==============================] - 0s 26us/sample - loss: 0.0705 - accuracy: 0.9771

 Test Accuracy: 0.9771
