In [3]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import numpy as np

In [7]:
# AND연산의  x1, x2입력을 저장하는 배열
X = np.array([
                [0., 0.],
                [0., 1.],
                [1., 0.],
                [1., 1.],
        ], dtype = "float32")

# AND연산의 y출력을 저장하는 배열
Y = np.array([0, 0, 0, 1], dtype = "int32")

In [8]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [9]:
Y

array([0, 0, 0, 1])

In [10]:
model = Sequential()
model.add(Dense(1, input_dim = 2, activation = "sigmoid"))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [11]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.compile(loss = 'binary_crossentropy', optimizer = Adam(lr = 0.1), metrics = ['acc'])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [14]:
model.fit(X, Y, epochs = 100)


Epoch 1/100
4/4 [==============================] - 0s 19ms/step - loss: 0.7317 - acc: 0.7500
Epoch 2/100
4/4 [==============================] - 0s 0us/step - loss: 0.6964 - acc: 0.7500
Epoch 3/100
4/4 [==============================] - 0s 0us/step - loss: 0.6688 - acc: 0.7500
Epoch 4/100
4/4 [==============================] - 0s 0us/step - loss: 0.6427 - acc: 0.5000
Epoch 5/100
4/4 [==============================] - 0s 0us/step - loss: 0.6188 - acc: 0.5000
Epoch 6/100
4/4 [==============================] - 0s 250us/step - loss: 0.5974 - acc: 0.5000
Epoch 7/100
4/4 [==============================] - 0s 500us/step - loss: 0.5782 - acc: 0.7500
Epoch 8/100
4/4 [==============================] - 0s 250us/step - loss: 0.5604 - acc: 0.7500
Epoch 9/100
4/4 [==============================] - 0s 250us/step - loss: 0.5434 - acc: 0.7500
Epoch 10/100
4/4 [==============================] - 0s 503us/step - loss: 0.5268 - acc: 0.7500
Epoch 11/100
4/4 [==============================] - 0s 250us/step -

Epoch 86/100
4/4 [==============================] - 0s 501us/step - loss: 0.1159 - acc: 1.0000
Epoch 87/100
4/4 [==============================] - 0s 250us/step - loss: 0.1145 - acc: 1.0000
Epoch 88/100
4/4 [==============================] - 0s 250us/step - loss: 0.1132 - acc: 1.0000
Epoch 89/100
4/4 [==============================] - 0s 500us/step - loss: 0.1118 - acc: 1.0000
Epoch 90/100
4/4 [==============================] - 0s 254us/step - loss: 0.1105 - acc: 1.0000
Epoch 91/100
4/4 [==============================] - 0s 751us/step - loss: 0.1093 - acc: 1.0000
Epoch 92/100
4/4 [==============================] - 0s 496us/step - loss: 0.1080 - acc: 1.0000
Epoch 93/100
4/4 [==============================] - 0s 500us/step - loss: 0.1067 - acc: 1.0000
Epoch 94/100
4/4 [==============================] - 0s 499us/step - loss: 0.1055 - acc: 1.0000
Epoch 95/100
4/4 [==============================] - 0s 250us/step - loss: 0.1043 - acc: 1.0000
Epoch 96/100
4/4 [==============================] 

In [15]:
pred = model.predict(X)
pred

array([[0.00260878],
       [0.11642373],
       [0.11689422],
       [0.869591  ]], dtype=float32)

In [16]:
predict01 = np.where(pred>0.5, 1, 0)
print("=======================================")
print(predict01)

[[0]
 [0]
 [0]
 [1]]


In [17]:
predict02 = predict01.flatten()
predict02

array([0, 0, 0, 1])

In [18]:
predict03 = (predict02 == Y)
predict03

array([ True,  True,  True,  True])

In [19]:
np.sum(predict03)

4

In [20]:
acc = np.sum(predict03)/4

In [21]:
acc

1.0