In [1]:
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()

In [2]:
# AND연산의  x1, x2입력을 저장하는 배열
X = np.array([
                [0., 0.],
                [0., 1.],
                [1., 0.],
                [1., 1.],
        ], dtype = "float32")

# AND연산의 y출력을 저장하는 배열
Y = np.array([
                [0.],
                [0.],
                [0.],
                [1.]
        ], dtype = "float32")

In [3]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [4]:
Y

array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)

In [5]:
# X에 곱해지는 값 선언
w = np.array([[1], [2]], dtype = "float32")
# X에 더해지는 값 선언
b = np.array([[3]], dtype = "float32")

In [6]:
w

array([[1.],
       [2.]], dtype=float32)

In [7]:
b

array([[3.]], dtype=float32)

In [8]:
# X에 w를 곱합
np.dot(X, w)

array([[0.],
       [2.],
       [1.],
       [3.]], dtype=float32)

In [9]:
# X에 w를 곱하고 b를 더함
np.dot(X, w) + b

array([[3.],
       [5.],
       [4.],
       [6.]], dtype=float32)

In [10]:
# h를 0 ~ 1 사이 범위로 변경하는 활성함수 선언
def sigmoid(h):
    return 1 / (1 + np.exp(-h))

In [11]:
# X * w + b 를 실행해서 예측값을 hypothesis에 대입
hypothesis = np.dot(X, w) + b
hypothesis

array([[3.],
       [5.],
       [4.],
       [6.]], dtype=float32)

In [12]:
# X * w + b 를 실행해서 예측값을 hypothesis에 대입하고 활성함수를 이용
# 값의 범위를 0 ~ 1 사이로 변경
hypothesis = sigmoid(np.dot(X, w) + b)
hypothesis

array([[0.95257413],
       [0.9933072 ],
       [0.98201376],
       [0.9975274 ]], dtype=float32)

In [13]:
# 예측값 - 실제값
(hypothesis - Y)

array([[ 0.95257413],
       [ 0.9933072 ],
       [ 0.98201376],
       [-0.00247258]], dtype=float32)

In [14]:
# X의 줄칸을 반대로 전환
X.T

array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]], dtype=float32)

In [15]:
# X의 줄칸을 반대로 전환하고 0번째 줄을 리턴
# X의 줄칸을 반대로 전환했기 때문에 실제로는 0번째 칸이 리턴됨
X.T[0]

array([0., 0., 1., 1.], dtype=float32)

In [17]:
# 이차원 배열인 (hypothesis - Y) 와 변환하기위해서
# X.T[0]를 2차원 배열로 변환
X_col_2d1 = X.T[0].reshape(1, -1)
X_col_2d1

array([[0., 0., 1., 1.]], dtype=float32)

In [18]:
# w1의 수정값
w1_gred = 1/4 * np.sum(np.dot(X_col_2d1, (hypothesis - Y)))
print(w1_gred)

0.24488529562950134


In [19]:
X.T[1]

array([0., 1., 0., 1.], dtype=float32)

In [20]:
X_col_2d2 = X.T[1].reshape(1, -1)
X_col_2d2

array([[0., 1., 0., 1.]], dtype=float32)

In [21]:
# w2의 수정값
w2_gred = 1/4 * np.sum(np.dot((hypothesis - Y), X_col_2d1))
print(w2_gred)

1.4627113342285156


In [22]:
# b의 수정값
b_gred = 1/4 * np.sum(hypothesis - Y)
print(b_gred)

0.731355607509613


In [23]:
learning_rate = 0.1

In [24]:
for i in range(100):
    for j in range(2):
        hypothesis = sigmoid(np.dot(X, w) + b)
        cost = -1/4 * (Y * np.log(hypothesis) + (1 - Y) * np.log(1 - hypothesis))
        X_col_2d = X.T[j].reshape(1, -1)
        w_gred = 1/4 * np.sum(np.dot(X_col_2d, (hypothesis - Y)))
        w[j] = w[j] - learning_rate * w_gred
        b_gred = 1/4 * np.sum(hypothesis - Y)
        b = b - learning_rate * b_gred

In [25]:
w

array([[0.7401471],
       [1.3791031]], dtype=float32)

In [26]:
b

array([[-2.0687358]], dtype=float32)

In [28]:
np.dot(X , w) + b

array([[-2.0687358 ],
       [-0.6896328 ],
       [-1.3285887 ],
       [ 0.05051446]], dtype=float32)

In [29]:
predict = sigmoid(np.dot(X, w) + b)
predict

array([[0.11217288],
       [0.33411476],
       [0.2093929 ],
       [0.51262593]], dtype=float32)

In [30]:
predict01 = tf.cast(predict > 0.5, dtype = tf.float32)
print(predict01)

tf.Tensor(
[[0.]
 [0.]
 [0.]
 [1.]], shape=(4, 1), dtype=float32)


In [31]:
ac01 = tf.equal(predict01, Y)
ac01

<tf.Tensor: id=3, shape=(4, 1), dtype=bool, numpy=
array([[ True],
       [ True],
       [ True],
       [ True]])>

In [32]:
ac02 = tf.cast(ac01, dtype = "float32")
ac02

<tf.Tensor: id=4, shape=(4, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>

In [33]:
ac03 = tf.reduce_mean(ac02)
ac03

<tf.Tensor: id=6, shape=(), dtype=float32, numpy=1.0>

In [34]:
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01, Y), dtype = tf.float32))
print(accuracy.numpy())

1.0


In [35]:
arr = np.array([[0, 1]], dtype = "float32")
predict = sigmoid(np.dot(arr, w) + b)
predict

array([[0.33411476]], dtype=float32)

In [36]:
predict = tf.cast(predict > 0.5, dtype = tf.float32)
predict.numpy()

array([[0.]], dtype=float32)

In [37]:
arr = np.array([[1, 1]], dtype = "float32")
predict = sigmoid(np.dot(arr, w) + b)
predict

array([[0.51262593]], dtype=float32)

In [38]:
predict = tf.cast(predict > 0.5, dtype = tf.float32)
predict.numpy()

array([[1.]], dtype=float32)