In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.enable_eager_execution()

In [3]:
# AND연산의  x1, x2입력을 저장하는 배열
X = np.array([
                [0., 0.],
                [0., 1.],
                [1., 0.],
                [1., 1.],
        ], dtype = "float32")

# AND연산의 y출력을 저장하는 배열
Y = np.array([
                [0.],
                [0.],
                [0.],
                [1.]
        ], dtype = "float32")

In [4]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [5]:
Y

array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)

In [6]:
# 선형 회귀 함수의 기울기를 저장할 w선언 기본값: 1, 2
w = tf.Variable([[1], [2]], dtype = "float32")
# 선형 회귀 함수의 절편을 저장할 b선언 기본값 3
b = tf.Variable([3], dtype = "float32")

In [7]:
w

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

In [8]:
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([3.], dtype=float32)>

In [9]:
# X와 w의 곱
tf.matmul(X, w)

<tf.Tensor: id=21, shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [2.],
       [1.],
       [3.]], dtype=float32)>

In [10]:
# X와 w의 곱하고 b 더하기
tf.matmul(X, w) + b

<tf.Tensor: id=26, shape=(4, 1), dtype=float32, numpy=
array([[3.],
       [5.],
       [4.],
       [6.]], dtype=float32)>

In [11]:
tf.sigmoid(tf.matmul(X, w) + b)

<tf.Tensor: id=32, shape=(4, 1), dtype=float32, numpy=
array([[0.95257413],
       [0.9933071 ],
       [0.98201376],
       [0.99752736]], dtype=float32)>

In [12]:
optimizer = tf.train.AdamOptimizer(0.01)

In [13]:
for step in range(5000):
    with tf.GradientTape() as tape:
        hypothesis = tf.sigmoid(tf.matmul(X, w) + b)
        cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
        grads = tape.gradient(cost, [w, b])
    
    optimizer.apply_gradients(grads_and_vars = zip(grads, [w ,b]))
    
    if step % 100 == 0:
        print("="* 50)
        print("step: {}, cost: {}, w: {}, b: {}".format(step, cost, w.numpy(), b.numpy()))

step: 0, cost: 3.0189805030822754, w: [[0.99]
 [1.99]], b: [2.99]
step: 100, cost: 1.8529284000396729, w: [[0.01112574]
 [1.0014889 ]], b: [2.0029898]
step: 200, cost: 1.0872455835342407, w: [[-0.71142066]
 [ 0.1846364 ]], b: [1.1350007]
step: 300, cost: 0.8457093834877014, w: [[-0.770385  ]
 [-0.11182883]], b: [0.52571815]
step: 400, cost: 0.7202606201171875, w: [[-0.4511011]
 [-0.0378984]], b: [0.06198945]
step: 500, cost: 0.6177883148193359, w: [[-0.07153893]
 [ 0.16270581]], b: [-0.3574327]
step: 600, cost: 0.5337925553321838, w: [[0.2775185 ]
 [0.39751324]], b: [-0.75495905]
step: 700, cost: 0.4659406542778015, w: [[0.5853591]
 [0.6383077]], b: [-1.1313304]
step: 800, cost: 0.41105544567108154, w: [[0.85861605]
 [0.8750348 ]], b: [-1.4864283]
step: 900, cost: 0.36615604162216187, w: [[1.1055076]
 [1.1035057]], b: [-1.8219204]
step: 1000, cost: 0.32885345816612244, w: [[1.3327839]
 [1.3223375]], b: [-2.1403055]
step: 1100, cost: 0.29735806584358215, w: [[1.5453968]
 [1.5316242]], b

In [14]:
w

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[7.047746],
       [7.039203]], dtype=float32)>

In [15]:
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-10.636642], dtype=float32)>

In [16]:
predict = tf.sigmoid(tf.matmul(X, w) + b)
predict

<tf.Tensor: id=315293, shape=(4, 1), dtype=float32, numpy=
array([[2.4020672e-05],
       [2.6663423e-02],
       [2.6885986e-02],
       [9.6924031e-01]], dtype=float32)>

In [17]:
predict01 = tf.cast(predict > 0.5, dtype = tf.float32)
print(predict01)

tf.Tensor(
[[0.]
 [0.]
 [0.]
 [1.]], shape=(4, 1), dtype=float32)


In [18]:
ac01 = tf.equal(predict01, Y)
ac01

<tf.Tensor: id=315298, shape=(4, 1), dtype=bool, numpy=
array([[ True],
       [ True],
       [ True],
       [ True]])>

In [19]:
ac02 = tf.cast(ac01, dtype = "float32")
ac02

<tf.Tensor: id=315299, shape=(4, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>

In [20]:
ac03 = tf.reduce_mean(ac02)
ac03

<tf.Tensor: id=315301, shape=(), dtype=float32, numpy=1.0>

In [21]:
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01, Y), dtype = tf.float32))
print(accuracy.numpy())

1.0
