In [1]:
import numpy as np
import pandas as pd

In [2]:
s = pd.Series([1,2,3,4,5]) # 1차원 배열 Series, 정수타입
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
s = pd.Series(['하나', '둘', '셋']) # 1차원배열 문자열 타입
s

0    하나
1     둘
2     셋
dtype: object

In [4]:
print(s)
print(type(s))

0    하나
1     둘
2     셋
dtype: object
<class 'pandas.core.series.Series'>


In [5]:
#날짜
dates = pd.date_range('2020-02-10', periods=7)
dates

DatetimeIndex(['2020-02-10', '2020-02-11', '2020-02-12', '2020-02-13',
               '2020-02-14', '2020-02-15', '2020-02-16'],
              dtype='datetime64[ns]', freq='D')

In [6]:
#2차원배열자료구조 DateFrame
dt = pd.DataFrame(np.random.randn(7,2), index = dates, columns=['A', 'B'])
dt

A         B
2020-02-10 -0.906096  0.117733
2020-02-11 -0.720148 -0.359053
2020-02-12  0.221231 -0.631983
2020-02-13  0.512514 -0.250468
2020-02-14  0.500557  0.077876
2020-02-15 -0.380088 -0.193758
2020-02-16 -0.570918  0.705643

In [7]:
df = pd.DataFrame(np.random.randint(10, 20, size=(7,2)), index = dates, columns=['A', 'B'])
df

A   B
2020-02-10  10  19
2020-02-11  16  19
2020-02-12  19  13
2020-02-13  19  14
2020-02-14  11  17
2020-02-15  11  14
2020-02-16  13  13

#columns ==> 'A', "B", 'C', 'D' 7행 4열 정수값 랜덤을 DateFrame으로
1~100 사이의 값을 출력

In [8]:
df = pd.DataFrame(np.random.randint(1, 101, size = (7, 4)), columns = ['A', 'B', 'C', 'D'])
df

A    B   C   D
0  28   22  20  48
1  87   21  80  64
2  75    6  47   3
3  58  100   8  13
4  16    5   6  32
5  41   53  75  62
6  98   79  21  87

In [9]:
df.values

array([[ 28,  22,  20,  48],
       [ 87,  21,  80,  64],
       [ 75,   6,  47,   3],
       [ 58, 100,   8,  13],
       [ 16,   5,   6,  32],
       [ 41,  53,  75,  62],
       [ 98,  79,  21,  87]])

In [10]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [11]:
df.index

RangeIndex(start=0, stop=7, step=1)

In [12]:
print(type(df.index))

<class 'pandas.core.indexes.range.RangeIndex'>


In [13]:
type(df.columns)

pandas.core.indexes.base.Index

In [14]:
type(df.values)

numpy.ndarray

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       7 non-null      int32
 1   B       7 non-null      int32
 2   C       7 non-null      int32
 3   D       7 non-null      int32
dtypes: int32(4)
memory usage: 240.0 bytes


In [16]:
df.describe()

A           B          C          D
count   7.000000    7.000000   7.000000   7.000000
mean   57.571429   40.857143  36.714286  44.142857
std    30.772591   37.306963  30.928489  29.930077
min    16.000000    5.000000   6.000000   3.000000
25%    34.500000   13.500000  14.000000  22.500000
50%    58.000000   22.000000  21.000000  48.000000
75%    81.000000   66.000000  61.000000  63.000000
max    98.000000  100.000000  80.000000  87.000000

In [17]:
#내림차순 정렬
df.sort_values(by='A', ascending = True)

A    B   C   D
4  16    5   6  32
0  28   22  20  48
5  41   53  75  62
3  58  100   8  13
2  75    6  47   3
1  87   21  80  64
6  98   79  21  87

In [18]:
df

A    B   C   D
0  28   22  20  48
1  87   21  80  64
2  75    6  47   3
3  58  100   8  13
4  16    5   6  32
5  41   53  75  62
6  98   79  21  87

In [19]:
df1 = df.sort_values(by='A', ascending = False)
df1

A    B   C   D
6  98   79  21  87
1  87   21  80  64
2  75    6  47   3
3  58  100   8  13
5  41   53  75  62
0  28   22  20  48
4  16    5   6  32

In [20]:
df['A']

0    28
1    87
2    75
3    58
4    16
5    41
6    98
Name: A, dtype: int32

In [21]:
df['B']

0     22
1     21
2      6
3    100
4      5
5     53
6     79
Name: B, dtype: int32

In [22]:
df['B'].values

array([ 22,  21,   6, 100,   5,  53,  79])

In [23]:
df1['A'].values

array([98, 87, 75, 58, 41, 28, 16])

In [26]:
#데이터 슬라이딩
df[:]

A    B   C   D
0  28   22  20  48
1  87   21  80  64
2  75    6  47   3
3  58  100   8  13
4  16    5   6  32
5  41   53  75  62
6  98   79  21  87

In [27]:
df[2:5]

A    B   C   D
2  75    6  47   3
3  58  100   8  13
4  16    5   6  32

In [30]:
df.loc[1:6, ['B', 'A', 'C']]

B   A   C
1   21  87  80
2    6  75  47
3  100  58   8
4    5  16   6
5   53  41  75
6   79  98  21

1~5까지 출력 D,B,A df 출력 loc[]사용

In [31]:
df.loc[1:6, ['D', 'B', 'A']]

D    B   A
1  64   21  87
2   3    6  75
3  13  100  58
4  32    5  16
5  62   53  41
6  87   79  98

In [33]:
df.loc[:,['A']]
df['A']
df.A

0    28
1    87
2    75
3    58
4    16
5    41
6    98
Name: A, dtype: int32

In [34]:
df[df.A > 50]

A    B   C   D
1  87   21  80  64
2  75    6  47   3
3  58  100   8  13
6  98   79  21  87

In [35]:
df.apply(lambda x : x.max() - x.min())

A    82
B    95
C    74
D    84
dtype: int64